# Generated by Django 3.1.14 on 2025-07-22 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicehistory',
            old_name='user',
            new_name='customer',
        ),
    ]
